---
title: ''
output: bookdown::pdf_document2
---

Climate change affects populations over broad geographic ranges due to spatially autocorrelated abiotic conditions known as the Moran Effect. However, populations do not always respond to broad-scale environmental changes synchronously across a landscape. We combined multiple data sets for a retrospective analysis of time-series count data (5-28 annual samples per segment) at 144 stream segments dispersed over nearly 1,000 linear kilometers of range to characterize the population structure and scale of spatial synchrony across the southern native range of a coldwater stream fish (brook trout, *Salvelinus fontinalis*), which is sensitive to stream temperature and flow variations. Spatial synchrony differed by life stage and geographic region: it was stronger in the juvenile life stage than the adult life stage and in the northern sub-region than the southern sub-region. Spatial synchrony of trout populations extended to 100-200 km but was much weaker than that of climate variables such as temperature, precipitation, and stream flow. Early life stage abundance changed over time due to annual variation in summer temperature and winter and spring stream flow conditions. Climate effects on abundance differed between sub-regions and among local populations within sub-regions, indicating multiple cross-scale interactions where climate interacted with local habitat to generate only a modest pattern of population synchrony over space. Overall, our analysis showed higher degrees of response heterogeneity of local populations to climate variation and consequently population asynchrony than previously shown based on analysis of individual, geographically restricted data sets. This response heterogeneity indicates that certain local segments characterized by population asynchrony and resistance to climate variation could represent unique populations of this iconic native coldwater fish that warrant targeted conservation. Advancing the conservation of this species can include actions that identify such priority populations and incorporate them into landscape-level conservation planning. Our approach is applicable to other widespread aquatic species sensitive to climate change.
