---
title: ''
output: pdf_document
---

## Synchrony
Spatial synchrony in SE US brook trout populations was moderate, especially when compared to highly synchronous climate variables such as temperature, precipitation, and flow. Climate is often considered to exert strong effects on temporal variation in animal and plant population size [@stenseth2002; @saether2004]. We utilized a compound spline correlogram that compared abiotic and biotic factors to create a novel comparison of synchrony. We hypothesized that patterns of spatial synchrony would be similar between climate variables and trout populations, if climate exerted a strong effect on population trajectories across space. The spline correlogram for juvenile density exhibited a similar shape to that of winter flow, with a defined dip at around 150km. Otherwise, spatial population synchrony of the native coldwater fish was modest in both magnitude and distance, and was much weaker than that of climate variables. Initial and average correlation among observed precipitation and temperature was over twice as strong as correlation among trout populations (Fig. \@ref(fig:compound-corrgram-plot)). The climate variables were also significantly autocorrelated at far greater distances than were trout populations. Patterns of synchrony were mostly dissimilar between abiotic and biotic factors, suggests that these climate variables are not exerting strong pressure on the synchrony of brook trout. The strength of spatial autocorrelation may have differed between the biotic and abiotic responses because trout populations responded to climate heterogeneously over space.

Our population model further demonstrated that populations of this coldwater species were only moderately synchronized. ICC values varied across the landscape, revealing both regional and local diversity in synchrony (Fig.\@ref(fig:YOY-ICC-map)). On average, northern populations were twice as synchronous as southern populations, likely a result of subregional differences in population responses to climate. As the more threatened subregional population, southern Appalachian brook trout may benefit from this asynchrony. The most synchronous populations were located in central Maryland and in Great Smoky Mountain National Park, however there were no characteristics of local habitat that particularly distinguished these stream segments. Young-of-year brook trout in Shenandoah National Park also showed elevated synchrony. Life stage differences in synchrony were also apparent. YOY fish populations were more synchronous than were adults, supporting prior indications that YOY brook trout experience higher synchrony than adults [@kanno2016]. This pattern of stronger synchrony in juvenile life stages is well-reflected in the literature, occurring in fish taxa from other salmonids [@cattaneo2003] to warm water and shoaling fish [@reyjol2008; @grenouillet2001]. 

It is important to recognize that inferences in population synchrony and heterogeneous responses depend inherently on geographic extent of investigations [@levin1992a; @wiens1989a], demonstrated similarly by our parallel analyses of regional versus sub-regional data. In brook trout, previous studies have reported stronger magnitude of spatial population synchrony than the current study, but they were much more limited in geographic extent [@kanno2016; @zorn2007b]. Estimates of the spatial scale of synchrony in freshwater populations vary widely [@myers1997; @copeland2011], however our estimates were in line with previous studies of brook trout [@kanno2016; @zorn2007b], as well as with other freshwater species [@tedesco2004]. Our macro-scale patterns emerged through analyses of multiple spatially and temporally replicated data sets (159 stream segments over 34 years) dispersed across over 100,000 km$^2$, and they provide a unique synthesis of climate vulnerability of this sensitive coldwater fish.


Our analysis revealed that climatic patterns in summer temperature and winter flow explained temporal variation in early-life-stage abundance, supporting the notion that coldwater stream fish in their range edges are sensitive to extremes of temperature and flow [@santiago2017]. Climate variables affected abundance of young-of-year trout, but not adult trout, over time. Life-stage-specific responses to stream flows are well documented in stream salmonids [@cattaneo2003; @kovach2016; @kanno2017]. Early life stages of trout suffer high mortalities when high flows mobilize stream bed substrates, as corroborated by diminished young-of-the-year abundance in summer following wet winter and spring in this fall-spawning species. In addition, young-of-the-year abundance decreased following hot summer in the previous year. Despite the fact that temperature effects were greater than those of flow, this pattern is less frequently documented in stream salmonids than flow effects [@kovach2016]. A potential mechanism is high adult mortality due to elevated summer temperature, which would lead to low spawner abundance in fall. However, our data show that adult abundance was not sensitive to temperature in the previous summer, and higher spawner abundance does not always result in higher recruitment in brook trout [@grossman2010; @kanno2016; @sweka2022]. Alternatively, this species delays or skips spawning in fall following hot summer [@warren2012], and this sub-lethal effect could lead to lower YOY abundance in the following year. Regardless of mechanisms, heterogeneous responses to climate variables between life stages may provide a demographic portfolio effect [@dybala2013; @schindler2010; @schindler2015], which can buffer brook trout populations from thermal and flow alterations to some extent. 

Climate effects on temporal animal abundance differed geographically at broad and fine spatial scales. As hypothesized, elevated temperature in the previous summer explained temporal variation in young-of-year trout abundance in the southern subregion more strongly than in the northern subregion. The magnitude of winter and spring flow effects on young-of-year trout abundance, however, was similar between the subregions. *continue from here when c-val issue is sorted out*

Stream segments differed in both spatial synchrony and in responses to climate. Correlation analysis reveals that neither the synchrony nor climate response of a given stream segment were closely related to local landscape and hydraulic characteristics. Could an unobserved local factor such as groundwater influence be responsible for the observed asynchrony? Or could there be other climate variables, as yet unidentified in the literature, that create asynchrony?

Climate refugia are of growing importance in ecological studies. Climate refugia are typically identified by abiotic characteristics [@ashcroft2010]. In the realm of coldwater fisheries, these abiotic characteristics are typically cool and stable water temperatures and buffered flows [@cartwright2018; @isaak2015]. Our methods, however, allow us to identify refugia using empirical biotic evidence. By measuring synchrony and asynchrony, we can identify locations and populations that are potentially resilient to climate stressors. A commonly identified weakness with traditional approaches to identifying refugia is that verification of refugia is seldom carried out [@barrows2020]. By identifying potential refugia using empirical biotic, evidence, we integrate the processes of identifying and validating climate refugia.

Spatially heterogeneous and asynchronous population responses to climate have implications for the conservation of this and other threatened species at their range edges. Previous studies assumed homogeneous and synchronous population responses to climate change in salmonids [@meisner1990; @rahel1996], and up to 97% habitat loss was projected for brook trout populations in the southern Appalachian Mountain streams [@flebbe2006], which corresponds to the southern sub-region of our current study. Although climate change is undeniably a major threat to the sensitive coldwater fish, our results demonstrate the importance of considering spatial heterogeneity and recognizing that some populations are more likely to persist than others in a changing climate. A key challenge lies in identifying a set of priority conservation populations in a landscape in an increasingly uncertain and non-stationary environment (REF). Our results inform this challenge. Priority conservation populations may be identified from gradients of population synchrony and heterogeneity to climate variation, so that a portfolio of populations with a range of climate responses could be targeted for protection and restoration to buffer against climate change impacts. This approach is applicable to other wide-ranging species with spatially and temporally replicated data sets.

####################################
Old discussion below:

## Drivers of abundance
Our findings support the notion that coldwater stream fish in their range edges are sensitive to extremes of temperature and flow, however we find that these effects can vary geographically and by life stage. Climate variables effected abundance of juveniles, but had little discernible effect on abundance of the adult life stage. *insert conclusive sentence about regional effects here* Abundance of YOY brook trout regionwide was negatively affected by summer temperatures, winter flows, and spring flows. Average summer high temperatures in the previous year had the strongest negative effect on YOY abundance, while maximum winter and spring flows both had small negative effects. Our results challenge those of @kanno2016, who found that winter flow had stronger negative effects on abundance than summer temperature. Subregional responses to climate differed. As hypothesized, southern populations near the edge of the native range were more susceptible to extremes of heat than were northern populations. *were northern pops particularly sensitive to anything?* We also observed a wide range of segment-specific responses to seasonal climate, evidence of strong cross-scale interactions possibly mediated by local habitat [@fridley2009]. Further work to relate local features to segment-specific responses to regional climate is ongoing.
Macrosystems research often reveals non-stationarity in covariate effects [@wiersma2022]. Our results are no different: we see that parameter estimates for climate covariates differed in space, even changing signs depending on the subregion in question. This non-stationarity in space is evidence of cross scale interactions.
* Since average high summer temperature was that of the previous year, how could it effect YOY abundance in year $t$? Those fish weren’t born yet when the temperatures happened. We think that these effects may result from nonlethal temperature effects on the parents of the YOY. 

## Drivers of synchrony

Maybe there are other covariates that are more important drivers of asynchrony?
*Come back to this later*We observed weak spatial synchrony arising from varying local responses to seasonal climate. Flows had the strongest synchronizing effects on YOY brook trout. Maximum winter flow had the largest contribution to synchrony of YOY, followed by maximum spring flow. Mean high summer temperature did not significantly contribute to synchrony of YOY. Since none of the three climate covariates considered had significant effects on adult abundance, none contributed significantly to adult synchrony. 

Given these low contributions and that we only considered three climate drivers in our analysis, it's likely that outside factors created the sycnchrony and asynchrony observed here. *Come back to this too*

## Local synchrony
We calculated a derived quantity (ICC) that allowed us to measure the synchrony of each population relative to others. As with population responses to climate, spatial synchrony varied by life stage and in space. YOY brook trout experienced higher synchrony than adults, likely a result of their increased sensitivity to climate drivers. A summer heat wave or winter flood may have the capacity to synchronize abundance of a year-class broadly across space. Spatial synchrony was slightly higher in northern brook trout populations than southern populations. Spatial heterogeneity and minimal spatial structure in ICC values indicate that synchrony may be mediated by local habitat as well. A correlation analysis reveals that the YOY ICC of a population is most correlated with stream segment elevation and fall streamflow (Spearman Correlation, 0.38 and 0.35). Five of the seven most synchronous populations (as measured by site-specific ICC values for YOY) were located in the southwest corner of North Carolina (Fig.\@ref(fig:YOY-ICC-map)). Young-of-year brook trout in Shenandoah National Park also showed elevated synchrony. These values tell us that 
* Asynchronous populations have important 

## Ecological Interpretations  
When compared to truly synchronous processes such as regional weather, we see that spatial synchrony in brook trout is relatively low no matter the scale. Combined with the finding that no climate variable exerts particularly strong influence on synchrony, these result indicate that brook trout populations may be relatively resilient to large-scale climate threats. Despite minimal spatial structure in synchrony, we found that it was relatively heterogeneous across the landscape, contributing to a portfolio of synchrony [@schindler2015]. Brook trout populations characterized by asynchrony and resistance to climate variation will likely persist as the southeastern USA warms and experiences increased precipitation. 

Climate refugia are of growing importance in ecological studies. Climate refugia are typically identified by abiotic characteristics [@ashcroft2010]. In the realm of coldwater fisheries, these abiotic characteristics are typically cool and stable water temperatures and buffered flows [@cartwright2018; @isaak2015]. Our methods, however, allow us to identify refugia using empirical biotic evidence. By measuring synchrony and asynchrony, we can identify locations and populations that are potentially resilient to climate stressors. A commonly identified weakness with traditional approaches to identifying refugia is that verification of refugia is seldom carried out [@barrows2020]. By identifying potential refugia using empirical biotic, evidence, we integrate the processes of identifying and validating climate refugia.


## Limitations and Future Directions
We attempt to account for dispersal of individuals between sites by summarizing counts and densities at the stream segment level. We assume that dispersal happens within, but not between stream segments. While individual brook trout have been known to migrate long distances, evidence suggests that population-level movement rarely exceeds the stream segment scale [@hudy2010; @rodriguez2002]. Future directions for this work would logically ensure spatial independence by sampling exclusively independent sites or by fitting a spatially explicit model.

How does summer temperature in year t-1 effect YOY in year t? @warren2012 found that elevated summer temperatures effect spawning time and redd construction by adult brook trout. We suspect that in years and at segments with high summer water temperatures, adults spawned with lower success, reducing recruitment to the following year class.

One limitation of using streamflow as a predictor in population models for coldwater organisms is that measured streamflow is not widely available for headwater streams. As done in our hierarchical model, the best alternative is often to use modeled streamflow for estimates at specific locations. Another alternative is to use modeled precipitation (DAYMET, PRISM), or measured precipitation from the nearest observation location (NOAA). Precipitation is an established stand-in for streamflow [@kanno2015; @kanno2016], however it cannot account for groundwater contributions to flow and the buffering effects of local landscape (i.e. forest cover, impoundments)[@zhu2019].

