---
title: ''
output: pdf_document
---

Our work synthesized count data from nine data sources at 144 sites over 34 years, which represents one of the most thorough attempts to understand spatiotemporal variation of stream fish populations across a large geographic region (~1,000 km). Count data of this spatiotemporal coverage are few in freshwater fish populations [@comte2021]. Our analysis reinforced previous findings that climate change would affect stream fish populations via altered temperature and flow patterns [@kovach2016]. Additionally, it revealed that local populations responded heterogeneously to climate variation across life stages. Cross-scale interactions [@heffernan2014] were also observed between and within sub-regions, resulting in modest spatial autocorrelation and population synchrony relative to highly spatially autocorrelated abiotic variables. These findings suggest that climate change impacts on sensitive aquatic populations will be complex and that not all populations are equally vulnerable to these threats [@ebersole2020]. Furthermore, they reinforce  the importance of population-level management for brook trout [@kazyak2022]. Our work highlights an opportunity and the need for embracing spatially heterogeneous population responses in range-wide planning for brook trout and other species of conservation concern.  

Spatial synchrony in trout populations was only modest when compared to highly synchronous temperature, precipitation, and stream flows, showing a first sign that the climate variables interacted with local conditions to generate spatially heterogeneous population responses. Previous studies of brook trout have reported stronger magnitude of spatial population synchrony than the current study, but they were much more limited in geographic extent [@kanno2016; @zorn2007]. Inferences on population synchrony depend inherently on geographic extent of investigations [@levin1992; @wiens1989], as further demonstrated by our parallel analyses of regional versus sub-regional data. Likewise, the identification of asynchronous outliers depends on the scale and distribution of sampling sites. Still, our estimated spatial scales of trout synchrony are comparable to those of other freshwater species [@copeland2011; @myers1997; @tedesco2004], and our average ICC values (i.e., magnitude of synchrony) were similar to those reported for other freshwater fish species [e.g., @michaletz2013; @midway2019] and considerably lower than those for terrestrial species [e.g., @canu2015; @grosbois2009; @lahoz-monfort2011]. Weaker synchrony of freshwater populations versus terrestrial populations may be due to stronger cross-scale interactions arising from fine-scale aquatic habitat heterogeneity [@benda2004; @mccluney2014] and physical isolation of habitats by watershed boundaries (e.g., headwater streams) that prevent movement of aquatic organisms [@liebhold2004; @ranta1995]. Additional research is warranted across taxa and ecosystems to elucidate relative strengths of these ecological mechanisms that determine magnitude and spatial scales of synchrony.

The most direct evidence of cross-scale interactions came from spatially heterogeneous climate effects on trout abundance. Our analysis showed that, when averaged across stream segments, YOY abundance was more sensitive than adult abundance to seasonal climate variation, a pattern commonly found in stream salmonids due mainly to vulnerability of the early life stage to substrate-mobilizing high flows and its diminished swimming abilities to cope with those disturbances [@kanno2016; @kanno2017; @kovach2016]. However, there was much variation among stream segments in the effect sizes (i.e., regression coefficients) of seasonal climate variables on trout abundance in this study. Importantly, the climate variables differed by spatial consistency in their effects on trout populations. Winter and spring stream flow both had similar negative effects on YOY abundance in both sub-regions, and while winter stream flow had the most spatially homogeneous effect on YOY abundance when sub-regions were combined in the N-mixture model. Additionally, the spline correlogram for YOY density exhibited the most similar shape to that of winter flow, with a defined dip at around 150 km Euclidean distance. It should be noted that as a modeled covariate, autocorrelation in stream flow at near distances was likely overestimated. Nonetheless, we reason that winter flow was the most important driver, among the three covariates tested, of the modest spatial autocorrelation and synchrony in YOY trout populations in this study. This inference is concerning regarding brook trout in the study area, which is projected to experience increased total precipitation during most of the year including winter [@alipour2020; @ingram2013; @portner2022]. Wildlife managers should consider restoration that increases the natural resilience of stream systems to flooding such as improving riparian cover and in-channel habitat complexity [@giller2005].

With the exception of summer air temperature effects on adults, climate effects were spatially heterogeneous between sub-regions. We interpret these cross-scale interactions in the context of latitudinal gradients along the north versus south sub-regions [@maitland2022], where the southern sub-region was warmer in summer and the northern sub-region experienced higher winter and spring stream flows (see Table \@ref(tab:sites-table)). Young-of-the-year abundance decreased following a hotter summer in the previous year in the southern, but not northern sub-region. A potential mechanism is high adult mortality due to elevated summer temperature, which would lead to low spawner abundance in fall [@grossman2010; @sweka2022]. However, adult responses to summer air temperature did not differ between sub-regions in this study. Alternatively, this species delays or skips spawning in fall and gamete development may be reduced following a hot summer due to stress or reduced body condition [@pankhurst2010; @warren2012], and these sub-lethal effects could lead to lower YOY abundance in the following year. We speculate that regional differences in spring flow or even latitudinal temperature shifts (see Table \@ref(tab:sites-table)) might explain why high spring flows resulted in lower YOY abundance mostly in the northern sub-region, because higher flows are more likely to result in stream bed scouring and or because warmer water temperature accelerates egg development in salmonids and hatch timing varies latitudinally [@fitzgerald2021; @yamamoto1997]. Consequently, YOY in northern populations may be more susceptible to high-flow-related mortality in spring than those in southern populations. Broad-scale studies of early life histories are needed to substantiate this hypothesis.

Although our analysis showed that climate effects on trout abundance differed among stream segments, our understanding is incomplete as to why the effects differed among them. Specifically, our exploratory analysis between segment-specific climate effects ($\bm{\beta}$) and spatial covariates (e.g., elevation, watershed area, channel slope) did not establish strong linkages. This lack of correlation suggests that other factors may be responsible for the observed complex cross-scale interactions [@soranno2014]. For example, groundwater discharge stabilizes temperatures over time and buffers aquatic habitat from warming [@brunke2003; @cartwright2018]. Groundwater influence can also provide suitable spawning and rearing habitat for fish [@blanchfield1997; @curry1995]. However, groundwater remains difficult to measure and predict over broad spatial scales such as that of our study [@kalbus2006]. Likewise, locally patchy habitat characteristics such as riparian shading and in-stream wood availability can be readily missed when characterizing stream habitat at broad scales [@fernandes2011; @wohl2018]. Localized extreme precipitation events are another factor with the potential to affect populations at small scales [@hickey1995]. We recommend fine-scale, long-term studies in representative networks throughout the range to more fully understand climate effects on aquatic populations.

As predicted, the climate effects on trout populations were stronger for the YOY stage. Life-stage-specific responses to flows are well documented in stream salmonids [@cattaneo2003; @kanno2017; @kovach2016]. Early life stages of trout suffer high mortality when elevated flows mobilize stream bed substrates, as corroborated in this study by diminished young-of-the-year abundance following wet winter and spring in this fall-spawning species. Because YOY abundance in the current year is a good predictor of adult abundance in the following year [@kanno2016; @kanno2017] and higher current adult abundance also typically leads to more YOY fish in the following year [@grossman2010; @sweka2022], climate effects on trout abundance could persist for more than a single year. That said, heterogeneous responses to climate variables between life stages may provide a demographic portfolio effect [@diamond2013; @dybala2013; @schindler2015] to buffer trout populations from climate change as long as unfavorable seasonal temperature and flow conditions do not occur frequently over consecutive years [@kanno2015].

Spatially heterogeneous and asynchronous population responses to climate have implications for the conservation of this and other threatened species at their range edges. Previous studies have assumed homogeneous and synchronous population responses to climate change in salmonids [@meisner1990; @rahel1996], and up to 97% habitat loss was projected for brook trout populations in the southern Appalachian Mountain streams [@flebbe2006], which corresponds to the southern sub-region of our current study. Although climate change is undeniably a major threat to the sensitive coldwater fish, our results demonstrate the importance of considering spatial heterogeneity and recognizing that some populations are more likely to persist than others in a changing climate. This finding underscores the importance of maintaining connectivity between populations, as it is often a range of small, diverse source populations that are responsible for persistence of a larger population [@tsuboi2022]. A key challenge lies in identifying a set of priority conservation populations in a landscape in an increasingly uncertain and non-stationary environment [@heller2009]. Our results inform this challenge by identifying highly asynchronous populations. Using gradients of population synchrony and heterogeneity to climate variation, priority conservation populations may be identified so that a portfolio of populations with a range of climate responses could be targeted for protection and restoration to buffer against climate change impacts [@raiho2022; @rosenberg2000]. In this study and others, asynchrony among local populations contributed to this portfolio, diminishing temporal variation in region-scale abundance when local populations were aggregated [@hilborn2003; @schindler2010; @schindler2015]. This type of landscape-level planning is most effective when coupled with abiotic data to identify populations that are most likely to be resilient to climate change (i.e., climate refugia) [@ashcroft2010; @cartwright2018; @larios-lopez2020; @morelli2020]. By investigating trends in population responses at multiple scales, our approach can inform conservation planning for an uncertain future. Finally, our methods are applicable to other wide-ranging aquatic species with spatially and temporally replicated data sets.
