---
title: ''
output: pdf_document
---

Synthesizing data from nine public and private data sources at 170 sites over 34 years, this work represents one of the most thorough attempts to understand spatiotemporal variation of stream populations over a broad spatial scale (~1,000 km). We found that a) spatial synchrony in populations of this threatened stream salmonid was only moderate, b) multiple cross-scale interactions with climate influences create heterogenous population responses across the study area, and c) brook trout life stages differ in both demographic (abundance and density) and emergent (synchrony and asynchrony) reactions to climate influence. Our results build on those of previous studies [e.g., @kanno2015, @kanno2016, @copeland2011, @zorn2007] by quantifying autocorrelation using multiple established methods and expanding the area of study to encompass the entire range edge of this valuable species. We continue to establish the importance of subannual [season-specific, e.g., @letcher2015] effects in ecological research as well as explore the existence of multi-scale and nested interactions. Lastly, our findings compliment recent genetic research that emphasizes fine-scale population structure in stream salmonids [@kazyak2022]. Our work highlights an opportunity and the need for embracing spatially heterogeneous populations responses in range-wide planning for brook trout and other species of conservation concern.

Spatial synchrony in SE US brook trout populations was low, especially when compared to highly synchronous climate variables such as temperature, precipitation, and flow. Average ICC values for YOY and adult fish were similar to those reported for other freshwater fish species [e.g., @michaletz2013; @midway2019] and considerably lower than estimates made for terrestrial species [e.g., @canu2015; @grosbois2009; @lahoz-monfort2011]. This is logical, as aquatic systems more closely meet assumptions of closure than do terrestrial ones. Climate is often considered to exert strong effects on temporal variation in animal and plant population size [@koenig2002; @stenseth2002; @saether2004]. Consequently, we hypothesized that patterns of spatial synchrony in the spline correlogram would be similar between climate variables and trout populations, if climate exerted a strong effect on population trajectories across space via the Moran Effect. Patterns of synchrony were moderately similar between abiotic and biotic factors, suggesting that these climate variables are exerting a weak synchronizing effect on populations of brook trout. Initial and average correlation among observed precipitation and temperature was over twice as strong as correlation among trout populations, and the spatial scale of synchrony in observed climate was also more than twice that of brook trout. The spline correlogram for juvenile density exhibited the most similar shape to that of winter flow, with a defined dip at around 150km. The variance in local effects of winter stream flow on juvenile abundance was also the smallest of the three climate variables. This implies winter stream flow as the strongest driver of what little synchrony is present in these populations. Winter stream flow has been suggested as a driver synchrony in other stream salmonids [@cattaneo2003]. The strength of spatial autocorrelation may have differed between the biotic and abiotic responses because trout populations responded to climate heterogeneously over space.

Synchrony was heterogeneous in space, as well as in population structure. Synchrony varied across the landscape, revealing both regional and local diversity in synchrony (Fig. \@ref(fig:YOY-ICC-map)). On average, northern populations were considerably more synchronous than southern populations, likely a result of sub-regional differences in population responses to climate. As the more threatened sub-regional population [@flebbe2006; @kazyak2022], southern Appalachian brook trout may benefit from their relative asynchrony. The most synchronous populations were located in eastern Maryland and in Great Smoky Mountain National Park, however there were no characteristics of local habitat that particularly distinguished these stream segments. Life stage differences in synchrony were also apparent. YOY fish populations were more than twice as synchronous than adults, supporting prior indications that YOY brook trout experience higher synchrony than adults [@kanno2016]. This pattern of stronger synchrony in juvenile life stages is well-reflected in the literature, occurring in fish taxa from other salmonids [@cattaneo2003] to warm water and shoaling fish [@reyjol2008; @grenouillet2001]. 

It is important to recognize that inferences in population synchrony and heterogeneous responses depend inherently on geographic extent of investigations [@levin1992; @wiens1989a], demonstrated similarly by our parallel analyses of regional versus sub-regional data. In brook trout, previous studies have reported stronger magnitude of spatial population synchrony than the current study, but they were much more limited in geographic extent [@kanno2016; @zorn2007]. Estimates of the spatial scale of synchrony in freshwater populations vary widely [@myers1997; @copeland2011], however our estimates were in line with previous studies of brook trout [@kanno2016; @zorn2007], as well as with other freshwater species [@tedesco2004]. Our macro-scale patterns emerged through analyses of multiple spatially and temporally replicated data sets (170 stream segments over 34 years) dispersed across over 100,000 km$^2$, and they provide a unique synthesis of climate vulnerability of this sensitive coldwater fish.

Our analysis revealed that climatic patterns in summer temperature and winter and spring flow explained temporal variation in early-life-stage abundance, supporting the notion that coldwater stream fish in their range edges are particularly sensitive to extremes of temperature and flow [@santiago2017]. Climate change is expected to bring warmer air temperatures and increased precipitation to the southeast USA [@portner2022; @alipour2020; @ingram2013]. Based on these projections, we expect decreased recruitment and increased mortality of YOY brook trout in the future. Climate variables affected abundance of young-of-the-year trout more than adult trout over time. Life-stage-specific responses to stream flows are well documented in stream salmonids [@cattaneo2003; @kovach2016; @kanno2017]. Early life stages of trout suffer high mortality when elevated flows mobilize stream bed substrates, as corroborated by diminished young-of-the-year abundance in summer following wet winter and spring in this fall-spawning species. These findings support our hypothesis that stream flow would have a stronger effect on the juvenile life stage than the adult stage. We also observed that young-of-the-year abundance in southern populations decreased following a hot summer in the previous year. This pattern is less frequently documented in stream salmonids than are flow effects [@kovach2016]. A potential mechanism is high adult mortality due to elevated summer temperature, which would lead to low spawner abundance in fall. Our data show that adult abundance was moderately sensitive to temperature in the previous summer, however this was in the northern populations, rather than the south, where juvenile experienced temperature effects. While low spawner abundance can result in low recruitment, higher spawner abundance does not always result in higher recruitment in brook trout [@grossman2010; @kanno2016; @sweka2022]. We observed a positive trend between spawner abundance and recruitment Fig. \@ref(fig:stock-recruitment-plot). Alternatively, this species delays or skips spawning in fall following hot summer [@warren2012], and this sub-lethal effect could lead to lower YOY abundance in the following year. Regardless of mechanisms, heterogeneous responses to climate variables between life stages may provide a demographic portfolio effect [@dybala2013; @schindler2010; @schindler2015], which can buffer brook trout populations from thermal and flow alterations to some extent. 

Climate effects on temporal animal abundance differed geographically at both broad and fine spatial scales, demonstrating multiple cross-scale interactions. As hypothesized, elevated temperature in the previous summer explained temporal variation in young-of-the-year brook trout abundance in the southern sub-region more strongly than in the northern sub-region. Populations of this coldwater fish inhabiting the southern extent of their range were indeed more sensitive to elevated temperatures. While spring flows had a negative effect on juvenile abundance in the south, they trended positive for juvenile abundance in the north. With earlier hatch dates, trout in southern populations may be more able to withstand late spring flows than those in northern populations. 

Within these broad-scale interactions, we also observed interactions at fine scales. While regional and sub-regional climate effects were mostly negative, individual population responses varied. Several populations had strong negative responses, while others experienced positive responses to climate - particularly spring flow. Our exploratory analysis between segment-specific climate effects ($\bm{\beta}$) and spatial covariates (e.g., elevation, watershed area, channel slope) did not identify their linkages. This lack of correlation suggests that other factors may be responsible for the observed complex cross-scale interactions [@soranno2014]. One possibility is population diversity: Southern Appalachian brook trout show considerable diversity even within and among drainages [@kazyak2022]. Genetic lineages may respond differently to environmental conditions - an important consideration in the determination of evolutionarily significant units [@waples1991; @nielsen1995; @kazyak2022]. Another possibility is an unobserved local habitat factor. Groundwater, for one, is an aspect of local habitat that can buffer the negative effects of temperature and flow [@cartwright2018; @brunke2003]. It can also provide superior spawning and rearing habitat for fish [@curry1995; @blanchfield1997]. Groundwater influence, however, remains difficult to measure and predict over broad spatial scales [@kalbus2006]. Likewise, stream shading riparian vegetation are a highly local habitat factor that is difficult to measure at broad scales but can buffer temperature and flooding. In fact, increasing evidence suggests that it is this highly-local habitat heterogeneity combined with diverse population responses that buffers synchrony and increases resilience via a portfolio effect [@schindler2010; @schindler2015; @hilborn2003]. This heterogeneity may also create climate refugia, critical to the long-term persistence of native species [@morelli2020; @larios-lopez2020]. Climate refugia are of growing importance in ecological studies. They are typically identified by local abiotic characteristics [@ashcroft2010; @cartwright2018]. However, a commonly identified weakness with traditional approaches to identifying refugia is that verification is seldom carried out [@barrows2020]. By identifying asynchronous populations, we can identify potential refugia using empirical biotic evidence, thus verifying their ecological function. Our methods allow us to identify locations and populations that are potentially resilient to climate stressors.

We fit two separate removal N-mixture models (i.e., climate effects models and random effects models). While this approach helps achieve model convergence (and our simulations suggest that parameters of models combining them should be identifiable), it has consequences for the range of possible inferences to be made. With no climate covariates in the random effects models, the two random effects absorb all temporal and spatiotemporal variance in density, and we cannot conclusively attribute spatial synchrony to specific climate drivers. Conversely, models lacking random effects overestimate the precision (i.e., underestimate 95% credible intervals) of regression coefficients such as climate covariate effects in our study, but their point estimates (i.e., posterior means) are much less affected [@schaub2012]. Therefore, our analysis should provide reliable inferences on the relative importance of temperature and flow effects and their spatial variation on trout abundance.

Spatially heterogeneous and asynchronous population responses to climate have implications for the conservation of this and other threatened species at their range edges. Previous studies assumed homogeneous and synchronous population responses to climate change in salmonids [@meisner1990; @rahel1996], and up to 97% habitat loss was projected for brook trout populations in the southern Appalachian Mountain streams [@flebbe2006], which corresponds to the southern sub-region of our current study. Although climate change is undeniably a major threat to the sensitive coldwater fish, our results demonstrate the importance of considering spatial heterogeneity and recognizing that some populations are more likely to persist than others in a changing climate. A key challenge lies in identifying a set of priority conservation populations in a landscape in an increasingly uncertain and non-stationary environment [@heller2009]. Our results inform this challenge. In this study and others, a portfolio effect diminished temporal variation in region-scale abundance [@hilborn2003; @schindler2010; @schindler2015]. Similar to the manner in which Essential Fish Habitat is identified and conserved in some marine jurisdictions [@rosenberg2000], priority conservation populations may be identified from gradients of population synchrony and heterogeneity to climate variation, so that a portfolio of populations with a range of climate responses could be targeted for protection and restoration to buffer against climate change impacts. This approach is applicable to other wide-ranging species with spatially and temporally replicated data sets.
