---
title: ''
output: pdf_document
date: "`r Sys.Date()`"
---

Populations commonly experience shared temporal variation in abundance or demographic rates across a landscape. This spatial synchrony is often the strongest between nearby populations due to spatially autocorrelated abiotic conditions, known as the Moran Effect [@moran1953; @royama1992] and biotic processes such as movement and predation [@koenig1999; @liebhold2004; @ranta1995]. Spatially homogeneous population responses have been reported for distances near 1,000 km in some animals and plants [@koenig1998; @post2002; @ranta1997]. Such broad-scale responses are attributed to continental and regional climate patterns, which are key drivers of demographic rates [@koenig2002; @stenseth2002]. The shared spatial scale of synchrony between climate drivers and population responses is typically regarded as a sign of the Moran Effect [@koenig1999; @moran1953]. As climate change accelerates, understanding the scale and drivers of spatial synchrony is critical to range-wide species conservation and management [@hansen2020].

Spatial synchrony as a result of climate is common in animals and plants, however local populations, even those in close geographical proximity, do not always display synchronous population trajectories [@herfindal2022; @sutcliffe1996]. Heterogeneous population responses result not only because the magnitude of climate variation differs over space but also because the capacity to buffer against it differs locally. This cross-scale interaction between a broad-scale driver (e.g., climate) and local populations can occur due to the fine-scale spatial heterogeneity created by features such as local topography, microclimate variation, and surface-groundwater exchange [@mclaughlin2017; @fridley2009]. As a result, the strength of cross-scale interactions determines how synchronously a set of local populations respond to broad-scale drivers [@granzotti2022]. A set of asynchronous population trajectories buffers species from range-wide declines [@heino1997; @roy2005], stabilizes populations over time at the regional scale [Portfolio Effect; @schindler2010; @schindler2015; @wilcox2017a], and increases socioeconomic resilience of resource use [e.g., hunting and angling, @cline2022]. However, little empirical knowledge exists about how synchronous and asynchronous populations are situated across the landscape in widely-distributed species.

Stream systems offer a unique opportunity for the study of macrosystems processes such as spatial synchrony and cross-scale interactions [@mccluney2014]. Streams are inherently characterized by spatial autocorrelation because downstream environmental patterns and processes such as temperature, biotic communities, and water chemistry are influenced by those upstream due to unidirectional flow [@isaak2017; @lloyd2005; @peterson2006a]. However, these processes do not typically prevail due to the spatial heterogeneity and network geometry created by stream confluences [@boddy2019; @frissell1986; @terui2018]. Confluences represent geomorphic breaks where physical habitat characteristics such as stream size, temperature, and channel slope change abruptly, creating spatial heterogeneity in abiotic conditions [@benda2004] and demographic responses [@childress2019] across stream networks. Consequently, stream habitat is often characterized and classified by segment [i.e., from confluence to confluence, @frissell1986; @USGS2016]. The stream segment is also the finest spatial grain at which stream habitat data are available at the national and continental scale (e.g., National Hydrography Dataset Plus (NHDPlus) data set in the USA). Stream confluences are more numerous and average segment length is shorter in headwaters than farther downstream in stream networks [@wohl2017]. Therefore, headwater stream networks contain habitat heterogeneity over relatively short physical distances, providing a template on which cross-scale interactions can occur.

Globally, headwater streams harbor a significant portion of remaining populations of coldwater fish such as trout and salmon, which are sensitive to variation in stream temperature and flow [@kovach2016]. Temperature and flow are key abiotic drivers of population and community dynamics in stream biota [@maheu2016; @poff1997]. Atmospheric air temperature, a key influence on and common surrogate for stream temperature, has increased steadily in the last century and is predicted to further increase [@portner2022]. In the southeast USA, climate change is projected to increase precipitation and the occurrence of extreme flood events [@alipour2020; @ingram2013]. Stream salmonids respond negatively to both high temperatures and high extremes of streamflow [@goode2013; @kanno2017; @mccullough2009; @santiago2017]. Climate effects on stream fish also vary by life stage and season. Early life stages of fish are sensitive to changes in streamflow. In particular, bed-scouring flows during incubation and emergence can wash away eggs and newly hatched individuals [@schlosser1985; @kovach2016; @cattaneo2002; @kanno2015]. As stronger swimmers, adults are less sensitive to high streamflow, however high water temperatures can result in increased stress and direct mortality, as well as impact spawn timing and reproductive success [@kovach2016; @pankhurst2010; @warren2012]. As climate change amplifies these effects, stream fish populations at the rear edges of their distributions are particularly vulnerable [@hampe2005; @pregler2018].

We characterized the climate drivers of spatial synchrony by life stage (i.e., juvenile and adult) among populations of an iconic native coldwater fish (brook trout, *Salvelinus fontinalis*) across multiple spatial scales in the southern portion of their native range in the eastern USA. Remnant populations of this salmonid in the study region occur in small, isolated headwaters [@kazyak2022], which limit potential for dispersal among headwater networks. Furthermore, predation impacts from other species are low as many populations occur in allopatry [@hudy2008], precluding dispersal and predation as factors that might otherwise synchronize population trajectories over space. Brook trout are highly sensitive to climate drivers such as stream temperature and flow [@kanno2017; @xu2010a; @warren2012; @roghair2002]. Consequently, this species provides an opportunity to investigate population synchrony attributable mainly to climate variation. 

Our study aims were threefold. First, we quantified the scale and strength of spatial synchrony among brook trout populations and compared it with those of spatial synchrony in climate variables (i.e., temperature, precipitation, and streamflow). We hypothesized that patterns of spatial synchrony would be similar between the climate variables and trout populations, if climate variables exerted a strong and spatially homogeneous effect on population trajectories [@koenig1999; @levin1992; @wiens1989]. Second, we tested whether spatial synchrony was explained by a set of seasonal climate variables and whether the importance of seasonal climate variables differed between and within northern and southern sub-regions. Because we studied a sensitive coldwater species at its southern range limit, we predicted that temperature would be a stronger driver of synchrony in southern populations compared to northern populations [@maitland2022]. Furthermore, we predicted that winter and spring stream flow would be a stronger driver of synchrony in the young-of-the-year (juvenile) stage versus adult stage of this fall spawner due to the diminished ability to withstand bed-scouring high flows of the younger stage [@kanno2016; @kovach2016]. Third, we quantified stream segment-specific population trajectories relative to the overall trajectory across segments to characterize how synchronous and asynchronous populations are distributed in the landscape. Asynchronous populations that deviate from the overall trajectory hold conservation value when asynchrony is due to population resiliency to environmental changes or habitat serving as climate refuge [@schindler2010; @schindler2015; @hilborn2003]. To address these aims, we assembled time-series abundance data at 144 stream segments spanning nearly 1,000 linear km of brook trout range across the southern Appalachian Mountains of the eastern USA.