---
title: "Spatial asynchrony and cross-scale climate interactions in populations of coldwater stream fish"
author: 
  - George P. Valentine, Dept. Fish, Wildlife, & Conservation Biology, Colorado State University, george.valentine@colostate.edu
  - Xinyi Lu, Dept. Fish, Wildlife, & Conservation Biology, Colorado State University
  - Evan Childress, Shenandoah National Park
  - C. Andrew Dolloff, U.S. Forest Service Southern Research Station
  - Nathanial Hitt, U.S. Geological Survey Eastern Ecological Science Center
  - Matthew Kulp, Great Smoky Mountains National Park
  - Benjamin Letcher, U.S. Geological Survey Eastern Ecological Science Center
  - Jacob Rash, North Carolina Wildlife Resources Comission
  - Mevin Hooten, Dept. Statistics & Data Sciences, University of Texas at Austin
  - Yoichiro Kanno, Dept. Fish, Wildlife, & Conservation Biology, Colorado State University, yoichiro.kanno@colostate.edu
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    toc: TRUE
    number_sections: TRUE
    keep_tex: true
geometry: "left = 2.5cm, right = 2cm, top = 2cm, bottom = 2cm"
fontsize: 11pt
header-includes:
  - \usepackage[left]{lineno}
  - \linenumbers
  - \pagenumbering{gobble}
  - \usepackage{sectsty}
  - \usepackage{setspace}\spacing{1.5}
  - \usepackage{bm}
  - \DeclareUnicodeCharacter{0008}{ }
  - \setlength{\parindent}{4em}
  - \usepackage{flafter}
linkcolor: blue
bibliography: bibliography.bib
csl: apa.csl
params:
  run_name: ["v2.0"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)

# load required R packages
library(here)         # For auto-locating files within the working directory
library(bookdown)     # For numbering figures, tables, and equations
library(stringr)      # For manipulating strings in figure captions
library(ncf)          # For creating correlograms in missing data simulation (Appendix 1)
library(cowplot)      # For creating gridded plots
library(gridGraphics) # For including base R plots in gridded plots
library(formatR)      # For displaying tidy code in output
library(knitr)        # For making tidy tables
library(forcats)      # For cats
library(latex2exp)    # For writing special characters in plot labels
library(kableExtra)   # For formatting tables
library(tinytex)

# Save the directory from which to pull results files
run_dir <- here::here("results", params$run_name)

# Load figures and tables to include
load(file = file.path(run_dir, "plots.rdata"))
load(file = file.path(run_dir, "tables.rdata"))
```

\newpage

# Abstract

```{r abstract, child = 'abstract.Rmd'}
```

\newpage
\pagenumbering{arabic}

# Introduction

```{r intro, child = 'introduction.Rmd'}
```

\newpage

# Methods

```{r methods, child = 'methods.Rmd'}
```

\newpage

# Results

```{r results, child = 'results.Rmd'}
```

\newpage

# Discussion

```{r discussion, child = 'discussion.Rmd'}
```

\newpage

# References

```{r biblio, child = 'bibliography.Rmd'}
```

\newpage

# Appendix

```{r appendix, child = 'appendix.Rmd'}
```
