---
title: ''
output: pdf_document
date: "`r Sys.Date()`"
---

# Methods
## Study Area and Dataset
* The study area for this analysis is the southern native range of Brook Trout, specifically the southeastern USA. Sites can be found from the southern Appalachian Mountains in northern Georgia to northern Maryland, with outliers as far north as Pennsylvania (\@ref{fig:sites_map.fig}). Areas such as Great Smoky Mountain National Park, Shenandoah National Park, and several long-term study sites have particularly high spatial and temporal coverage. We divided the northern and southern subregions at 37.13$^\circ$ latitude – that of Radford, VA in the New River Valley.
```{r sites_map, fig.cap = "Sites considered in this analysis"}
sites_map.plot
```

* Brook Trout data were compiled from 13 state and federal sources across the Eastern US (\@ref(tab:sources_table)).
* Our dataset consisted of (1) individual trout observations, (2) sample-level observations, and (3) site-level details. Individual trout observations include total length (mm) and weight (g). Sample-level observations include date and number of electrofishing passes. Site-level details include National Hydrography Dataset Plus (NHDPlus) stream segment common identifier (COMID), latitude and longitude (decimal degrees), elevation (m), length and average width (m).
* All data were collected by backpack electrofishing in wadeable streams between 1958 and 2020. Most of the sampling occurred in yearly summer surveys conducted at the same sites by fisheries managers and technicians, although rare and one-off surveys at new sites are present as well. Samples taken in lakes and ponds, as well as those of hatchery-born fish, were excluded. We accounted for measurement errors by removing individuals with weight >2 SD from the mean of each 10mm length category following @harris2020. Missing elevations were estimated with the Amazon Terrain Tiles elevation model using the elevatr package in R [@amazon2017; @hollister2021; @rcoreteam2022].
* YOY Brook Trout were defined as those <= 90mm total length, while adults were defined as those >90mm total length.
* An important consideration for our analyses was the scale of autocorrelation. Since synchrony can arise from individual dispersal, we summarized Brook Trout observations at a scale equal to greater than that at which the species typically disperses. While some individual in some populations have been known to move great distances [@gowan1994], southern Appalachian Brook Trout typically remain within several hundred meters of their hatching locations [@hudy2010; @rodriguez2002]. For this reason and to allow the association of segment-level covariates with our data, we analyzed Brook Trout observations by stream segment, defined by the USGS as a reach of a stream delineated by either its beginning and a confluence, or by two confluences. The average stream segment length within our dataset is 3.22 km.

## Correlogram Analysis
* We quantified the scale of spatial synchrony using nonparametric spatial covariance functions in the *ncf* package for R [@bjornstad2022; @bjornstad2001], from which we extracted estimates of both initial and average spatial correlation and the distances at which spatial covariance occurs. We define the scale of synchrony as the distance at which the correlation between two sites is significantly higher than the sample average. This scale is commonly referred to as correlation length [@bjornstad2001].
* We visually represented synchrony using spline correlograms, which portray the spatial decay in pairwise correlation between sites. In the context of a correlogram, the correlation length may be interpreted as the shortest distance at which the confidence envelope of the spline function intercepts the x-axis.
* We analyze synchrony separately by age class because Brook Trout life history suggests that YOY and adults are affected by different environmental drivers. Newly hatched fry are poor swimmers, and can be swept away by winter and spring flooding that adults can otherwise withstand. We also separate age classes because prior research suggests that YOY can display synchrony even when adults don’t [@kanno2016].
* In addition to analyzing age classes separately at the regional level, we further analyzed them separately at the subregional level. Again, we used the 37.13$^\circ$ line of latitude as a cutoff.
* We selected for sites with $\geq$ 5 years of data (hereafter “long term sites”) to ensure longevity in time series. We further filtered for observations made between the years 1980 and 2015, where density of surveys was highest and when covariates were available for the population model. Lastly, for this analysis we considered only multipass electrofishing data, which allows abundance estimates based on depletion.
* Abundances at each sample were predicted using the “removal” function in the *FSA* package for R [@ogle2022].
* Using these predicted abundances, we then calculated average abundance for each year, and from there the natural log of average density (fish/1000 m$^2$). This resulted in a measurement at each unique and segment and year.
* For stream segments and years where data were not collected (__% of observations), we substituted average log density for the given segment during the study period.
* We calculated 95% confidence intervals on the correlograms using the bootstrap algorithm included in the *ncf* package.
* We truncated pairwise distances to 2/3 the total distance observed following @fletcher2018.

## N-Mixture Model
* We used a Bayesian hierarchical N-mixture model [@royle2004] to measure synchrony in Brook Trout populations and to identify drivers of synchronous dynamics. This model structure also allows us to quantify covariate effects on abundance.
* Bayesian methods, which define probabilistic distributions of parameters given data, can more readily describe parameter uncertainty than can null hypothesis testing [@wade2000].
* We modeled the natural log of Brook Trout density (fish/1000 m$^2$) as a function of the environmental variables average 90th percentile summer temperature in the previous year, maximum 90th percentile winter flow, and maximum 90th percentile spring flow. Temperature predictions were obtained from the DAYMET model [@thornton2014; @thornton1997; @thornton2021] using the *daymetr* package in R [@hufkens2018]. Flow predictions were obtained from the NHDPlus V2 [@USGS2016]. These summary variables were calculated for the years 1981 – 2015 (the earliest year for which DAYMET data were available and the latest year for which flow estimates were available). We defined summer as June – September, winter as December - February, and spring as March – May.
* Adapting the standard N-mixture model to allow our removal sampling data at unique site $i = 1,...,n$, and year $t = 1,...,T$ for each of $j = 1,...,3$ electrofishing passes, we create the data model 
$$
\begin{equation}
  y_{i,1,t} \sim \text{binomial}(N_{i,t}, p_s)
  (\#eq:observationModel1)
\end{equation}
$$
for pass $j = 1$ where $N_{i,t}$ is abundance in year $t$ at reach $i$. Here, $p_s$ represents the detection probability for data source $s = 1, ...,S$.
* For subsequent electrofishing passes ($j > 1$), we model the observed removal sampling data as
$$
\begin{equation}
  y_{i,j,t} \sim \text{binomial}(N_{i,t} - \sum_{j=1}^{J}y_{i,j,t}, p_s)
  (\#eq:observationModel2)
\end{equation}
$$
because there are $\sum_{j=1}^{J}y_{i,j,t}$ fewer individuals in the population after removing them in each pass.
* We modeled abundance conditional on local density $\lambda_{i,t}$ (fish/1000m$^2$) as
$$
\begin{equation}
  N_{i,t} \sim \text{Poisson}(\frac{a_i}/{1000}\lambda_{i,t})
  (\#eq:processModel1)
\end{equation}
$$
where $a_i$ is the area of the given stream segment. Local density was represented as a function of segment-level environmental covariates $\bf{x}_{i,t}$ using the log-link function
$$
\begin{equation}
  \text{log}(\lambda_{i,t}) = \alpha_i + \bf{x}_{i,t}\bf{\beta} + \epsilon_t + \gamma_{i,t}
  (\#eq:processModel2)
\end{equation}
$$
where $\epsilon_t$ and $\gamma_{i,t}$ represent spatially- and spatiotemporally-structured random effects, respectively. Priors on $\alpha_i$ and $\bf{\beta}$ were $\alpha_i \sim \text{normal}(0, 1000)$ and $\bf{\beta} \sim \text{normal}(\bf{\mu}_\beta, \bf{\sigma}^2_\beta)$ where $\bf{\mu}_\beta \sim \text{normal}(0, 100)$ and $\bf{\sigma}_\beta) \sim \text{uniform}(0, 10)$.
* The random effects are assumed to be independent with distributions $\epsilon_t \sim \text{normal}(0, \sigma^2_\epsilon)$ X $\sigma^2_\epsilon \sim \text{uniform}(0, 10)$ and $\gamma_{i,t} \sim \text{normal}(0, \sigma^2_{\gamma,i})$ X $\sigma_{\gamma,i} \sim \text{uniform}(0, 10)$. The $\epsilon_t$ term represents the between-year variation in density that is synchronous to all sites, and the $\gamma_{i,t}$ term represents the variation that is site-specific, i.e. asynchronous. 
* Following @grosbois2009 and @lahoz-monfort2011, we then use the estimated variances of the two random effect terms to calculate a segment-specific intraclass correlation coefficient (ICC):
$$
\begin{equation}
  ICC_i = \frac{\hat{\sigma}^2_\epsilon}{\hat{\sigma}^2_\epsilon + \hat{\sigma}^2_{\gamma,i}}
  (\#eq:ICC)
\end{equation}
$$
This ICC value serves as a measure of the relative snchrony of the subpopulation in segment $i$ relative to the population as a whole. Large ICC values indicate that the given subpopulation is synchronous with the larger population, while small ICC values indicate asynchrony.
* The effects of environmental covariates on both overall and reach-specific synchrony can be calculated by comparing variances from two models: a model with environmental covariate(s) and an null model with no environmental covariates. Following @grosbois2009 and @lahoz-monfort2011, we calculate $C_\epsilon$ and $C_\gamma$:
$$
\begin{equation}
  \begin{align}
  C_\epsilon &= \frac{\hat{\sigma}^2_\epsilon(\text{res})}{\hat{\sigma}^2_\epsilon(\text{tot})}
  (\#eq:C_eps)
  C_\gamma &= \frac{\hat{\sigma}^2_{\gamma,i}(\text{res})}{\hat{\sigma}^2_{\gamma,i}(\text{tot})}  
  (\#eq:C_gam)
  \end{align}
\end{equation}
$$
* We fit a total of fourteen models: one full model and one null model each for YOY and adults, as well as one partial model per covariate each for YOY and adults. These models fit to all sites are hereafter the “regional” models. We further fit a full model each for YOY and adults in the northern and southern halves of the study region, hereafter the “subregional” models.
* We implemented our models utilizing Markov Chain Monte Carlo (MCMC) sampling using JAGS with the *jagsUI* package in R [@kellner2021]. Code can be found in Appendix X.
* After a burn-in period of 25,000 samples (50,000 for subregional models), three chains were run until 100,000 iterations were reached. We used a  thinning rate of 1.
* To evaluate the performance of our model, we completed posterior predictive checks for  mean and coefficient of variation.
* We report posterior means as point estimates and 95% highest posterior density credible intervals as estimates of uncertainty.